apiVersion: config.openshift.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: cluster
spec:
  domain: apps.openshift-lima.openshift-local.com
  loadBalancer:
    platform:
      type: ""
status:
  defaultPlacement: Workers
