apiVersion: config.openshift.io/v1
kind: DNS
metadata:
  creationTimestamp: null
  name: cluster
spec:
  baseDomain: openshift-lima.openshift-local.com
  platform:
    aws: null
    type: ""
status: {}
