apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  namespace: openshift-cluster-version
  name: version
spec:
  channel: stable-4.17
  clusterID: 7d809b96-fbb1-4976-957c-5d33f96adee3
